name: Quarto render and Publish

on:
  push:
    branches:
      - main

permissions: 
    contents: write
    pages: write

jobs:
  quarto-render-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
          
      # NOTE: If Publishing to GitHub Pages, set the permissions correctly
      - name: Publish to GitHub Pages (and render) 
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
